# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: 'en-US'

tone_instructions: >
  Be direct. Focus on bugs, perf, React 19 best practices. Skip style issues
  (ESLint/Prettier). No JSDoc, PropTypes, defaultProps, TS conversion, barrels.

reviews:
  profile: 'chill'
  high_level_summary: true
  high_level_summary_in_walkthrough: false
  poem: false
  sequence_diagrams: true
  collapse_walkthrough: true
  request_changes_workflow: false

  # Ignore generated/vendor files
  path_filters:
    - '!dist/**'
    - '!node_modules/**'
    - '!pnpm-lock.yaml'
    - '!coverage/**'
    - '!**/*.min.js'
    - '!**/*.min.css'
    - '!public/locales/**' # translation files - separate review process
    - '!storybook-static/**'
    - '!playwright-report/**'
    - '!**/__tests__/**' # unit tests - not worth reviewing

  path_instructions:
    # React components
    - path: 'src/components/**/*.{jsx,tsx}'
      instructions: |
        Review React 19 components for:
        - Proper hook usage (dependency arrays, cleanup in useEffect)
        - Unnecessary re-renders (missing memo, useMemo, useCallback where beneficial)
        - Accessibility (ARIA attributes, semantic HTML)
        - Component imports should be from folders, not direct files
        - Tailwind CSS v4 + shadcn/ui patterns
        - No console.log (console.warn/error allowed)
        - Control flow: always use curly braces with if statements on new lines

    # Custom hooks
    - path: 'src/hooks/**/*.{js,ts}'
      instructions: |
        Review custom hooks for:
        - Proper cleanup in useEffect
        - Correct dependency arrays
        - Return value memoization where appropriate
        - Clear naming (use* prefix)

    # Routing configuration
    - path: 'src/routes/**/*.{js,jsx,ts,tsx}'
      instructions: |
        Review routing code for:
        - Route guard logic (PublicRoute, PrivateRoute with requireStatuses)
        - ErrorBoundary proper error catching and Sentry integration
        - Layout/route hierarchy consistency
        - Correct status arrays (userActiveStatuses, adminActiveStatuses)
        - All routes should have errorElement
        - RootRedirect logic for authenticated/unauthenticated users

    # Pages/routes
    - path: 'src/pages/**/*.{jsx,tsx}'
      instructions: |
        Review page components for:
        - TanStack Query usage (loading/error states, proper query keys)
        - Route guard compatibility (PublicRoute vs PrivateRoute)
        - Role-based access considerations (admin vs user)

    # Context providers
    - path: 'src/contexts/**/*.{jsx,tsx}'
      instructions: |
        Review Context API implementations for:
        - Proper memoization of context values
        - Clear provider/consumer patterns
        - Existing contexts: Theme, Locale, Modal, Toast, Notification

    # Backend service layer (HTTP calls)
    - path: 'src/services/backend/**/*.{js,ts}'
      instructions: |
        Review backend service functions for:
        - Proper error handling
        - JWT token handling
        - Request/response structure
        - Base URL and endpoint consistency

    # Auth and admin hooks (TanStack Query)
    - path: 'src/hooks/use{Auth,Admin}*.{js,ts}'
      instructions: |
        Review TanStack Query hooks for:
        - Proper query keys (unique, consistent)
        - Loading/error state handling
        - Mutation side effects (onSuccess, onError)
        - Optimistic updates where appropriate
        - Cache invalidation patterns

    # Form handling
    - path: 'src/**/*Form*.{jsx,tsx}'
      instructions: |
        Review forms for:
        - React Hook Form + Yup validation pattern
        - Proper error display
        - Loading states during submission
        - i18n for validation messages

    # Utilities and lib
    - path: 'src/lib/**/*.{js,ts}'
      instructions: |
        Review utilities for:
        - Pure function patterns
        - TypeScript type safety
        - Error handling
        - Prefer const over let

    # E2E tests
    - path: 'e2e/**/*.{js,ts}'
      instructions: |
        Review Playwright E2E tests for:
        - Stable selectors (data-testid preferred)
        - Proper async/await handling
        - Test isolation

    # Storybook stories
    - path: '**/*.stories.{js,jsx,ts,tsx}'
      instructions: |
        Review Storybook stories for:
        - Comprehensive component states coverage
        - Proper controls/args setup
        - Documentation quality

    # Configuration files
    - path: 'vite.config.{js,ts}'
      instructions: |
        Check for:
        - Path aliases matching tsconfig (@/, @components)
        - Build optimization settings
        - Env variable handling

    - path: 'tailwind.config.{js,ts}'
      instructions: |
        Check Tailwind v4 configuration for:
        - shadcn/ui compatibility
        - Custom theme extensions
        - Content paths

  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - 'WIP'
      - 'DO NOT MERGE'
      - '[skip ci]'
      - '[skip review]'

  tools:
    biome:
      enabled: true
    eslint:
      enabled: true
    markdownlint:
      enabled: true
    gitleaks:
      enabled: true
    actionlint:
      enabled: true
    languagetool:
      enabled: true
      enabled_only: false
      level: 'default'

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: 'local'
  code_guidelines:
    enabled: true
    filePatterns:
      - 'CLAUDE.md'
      - '.claude/skills/**/*.md'
      - 'CONTRIBUTING.md'
      - '.cursorrules'
