coverage:
  status:
    project:
      default:
        target: 50%
        informational: true
    patch: off

  range: 50..75
  round: down
  precision: 0

ignore:
  - 'src/**/*.stories.{js,jsx}'
  - 'src/**/*.test.{js,jsx}'
  - 'src/**/*.spec.{js,jsx}'
  - 'src/tests/**'
  - 'src/index.jsx'
  - 'src/App.jsx'
  - 'src/i18n.js'
  - 'src/main.js'

comment:
  layout: 'reach,diff,flags,tree,footer'
  behavior: default
  require_changes: false
